### ISSUE TITLE
XML parsing problem in Eclipse Oxygen

### ISSUE THREAD

**Issue by demonfiddler** [acanda/eclipse-pmd#53] opened 2017-11-15 10:51 UTC
Running on Eclipse Oxygen.1A, I'm seeing entries like this in the Error Log:
Could not run PMD on file C:/source/workspaces/pmd-test/maven-experiments/target/surefire-reports/TEST-my.experiments.test.TestMyArrayList.xml
net.sourceforge.pmd.PMDException: Error while processing TEST-my.experiments.test.TestMyArrayList.xml
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:103)
	at ch.acanda.eclipse.pmd.builder.Analyzer.runPMD(Analyzer.java:79)
	at ch.acanda.eclipse.pmd.builder.Analyzer.analyze(Analyzer.java:65)
	at ch.acanda.eclipse.pmd.builder.PMDBuilder.analyze(PMDBuilder.java:79)
	at ch.acanda.eclipse.pmd.builder.PMDBuilder$ResourceVisitor.visit(PMDBuilder.java:126)
	at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at ch.acanda.eclipse.pmd.builder.PMDBuilder.fullBuild(PMDBuilder.java:65)
	at ch.acanda.eclipse.pmd.builder.PMDBuilder.build(PMDBuilder.java:51)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.IllegalArgumentException: interface org.apache.xerces.dom.DeferredNode is not visible from class loader
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Unknown Source)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Unknown Source)
	at java.lang.reflect.WeakCache$Factory.get(Unknown Source)
	at java.lang.reflect.WeakCache.get(Unknown Source)
	at java.lang.reflect.Proxy.getProxyClass0(Unknown Source)
	at java.lang.reflect.Proxy.newProxyInstance(Unknown Source)
	at net.sourceforge.pmd.lang.xml.ast.XmlParser.createProxy(XmlParser.java:88)
	at net.sourceforge.pmd.lang.xml.ast.XmlParser.parse(XmlParser.java:71)
	at net.sourceforge.pmd.lang.xml.XmlParser.parse(XmlParser.java:36)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:113)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:97)
	... 29 more

**Comment by acanda** [comment] 2017-11-15 13:04
I've come across this problems a couple of times in the past years but could never reliably reproduce it. It seems to be a class loader issue and might depend on the order in which the Eclipse plugins are activated or used.

What I know is that PMD uses Proxy.newProxyInstance(classloader, interfaces, ..) to create an XmlNode when parsing XML files. The list of interfaces sometimes contains interfaces loaded by different class loaders which the class loader passed to newProxyInstance cannot handle.

I think (but couldn't confirm it so far) that PMD's processor for XML files doesn't work correctly when run in a multi class loader environment like OSGi. It seems to be an issue that has to be resolved by PMD not eclipse-pmd.

**Closed** 2019-02-24 17:04 UTC
Labels: wontfix
